version: '3.3'

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/elian/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/elian/data/wordpress

# minha rede interna dos containers ======================

networks:
  inception:
    driver: bridge

# os meus lindos e incriveis serviçoes ====================

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    env_file: .env
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    env_file: .env
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    env_file: .env
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception

# parte bônus ======================================

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    restart: on-failure
    volumes:
    - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    image: ftp
    env_file: .env
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wordpress:/home/elian/ftp/files
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    networks:
      - inception

  website:
    build: ./requirements/bonus/website
    container_name: website
    image: website
    restart: on-failure
    ports:
      - "4444:4444"
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    restart: on-failure
    depends_on:
      - mariadb
    ports:
      - "600:80"
    networks:
      - inception

  fail2ban:
    build: ./requirements/bonus/fail2ban
    container_name: fail2ban
    image: fail2ban:latest
    restart: unless-stopped
    depends_on:
      - nginx
    volumes:
      - wordpress:/var/www/wordpress:ro
      - /var/log/nginx:/var/log/nginx:ro
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
