version: '3.3'

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/elian/data/mariadb
      o: bind

  wordpress:
    driver_opts:
      type: none
      device: /home/elian/data/wordpress
      o: bind

  adminer:
    driver_opts:
      type: none
      device: /home/elian/data/adminer
      o: bind

networks:
  inception:
    driver: bridge

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: unless-stopped
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx
    depends_on:
      - wordpress
    container_name: nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - inception

  adminer:
     build: ./requirements/bonus/adminer
     image: adminer
     depends_on:
       - mariadb
     container_name: adminer
     volumes:
      - adminer:/var/www/adminer
     ports:
       - "600:80"
     restart: on-failure
     networks:
       - inception

  website:
    build: ./requirements/bonus/website
    image: website
    container_name: website
    ports:
      - "4444:4444"
    restart: on-failure
    networks:
      - inception
