version: '3.3'

secrets:
  db_pass:
    file: ../secrets/db_pass.txt
  db_root_pass:
    file: ../secrets/db_root_pass.txt
  wp_editor_pass:
    file: ../secrets/wp_editor_pass.txt
  wp_user_pass:
    file: ../secrets/wp_user_pass.txt

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/elian/data/mariadb
      o: bind

  wordpress:
    driver_opts:
      type: none
      device: /home/elian/data/wordpress
      o: bind

  adminer:
    driver_opts:
      type: none
      device: /home/elian/data/adminer
      o: bind

networks:
  inception:
    driver: bridge

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:42
    container_name: mariadb
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    secrets:
      - db_pass
      - db_root_pass
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:42
    depends_on:
      - mariadb
    container_name: wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - WP_TITLE=${WP_TITLE}
      - WP_USER=${WP_USER}
      - WP_EMAIL=${WP_EMAIL}
      - WP_USER2=${WP_USER2}
      - WP_EMAIL2=${WP_EMAIL2}
    secrets:
      - db_pass
      - wp_editor_pass
      - wp_user_pass
    volumes:
      - wordpress:/var/www/wordpress
    restart: unless-stopped
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx:42
    depends_on:
      - wordpress
    container_name: nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_USER=${DB_USER}
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - inception

  adminer:
     build: ./requirements/bonus/adminer
     image: adminer:42
     depends_on:
       - mariadb
     container_name: adminer
     volumes:
      - adminer:/var/www/adminer
     ports:
       - "600:80"
     restart: on-failure
     networks:
       - inception

  website:
    build: ./requirements/bonus/website
    image: website:42
    container_name: website
    ports:
      - "4444:4444"
    restart: on-failure
    networks:
      - inception
