version: '3.3'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    expose:
      - "3306"

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
      - WP_EMAIL=${WP_EMAIL}
      - WP_TITLE=${WP_TITLE}
      - WP_URL=${WP_URL}
    expose:
      - "9000"

  nginx:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/elian/data/wordpress
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/elian/data/database

networks:
  inception_network:
    driver: bridge
