version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    secrets:
      - db_root_password
      - db_password

  mysql-client:
    build:
      context: ./requirements/mysql-client
      dockerfile: Dockerfile
    container_name: mysql-client
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./efaustin/data/mariadb

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt

