secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/efaustin/data/mariadb
      o: bind

  wordpress:
    driver_opts:
      type: none
      device: /home/efaustin/data/wordpress
      o: bind

  adminer:
    driver_opts:
      type: none
      device: /home/efaustin/data/adminer
      o: bind

  website:
    driver_opts:
      type: none
      device: /home/efaustin/data/website
      o: bind

networks:
  inception:
    driver: bridge

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:42
    container_name: mariadb
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:42
    depends_on:
      - mariadb
    container_name: wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - WP_TITLE=${WP_TITLE}
      - WP_USER=${WP_USER}
      - WP_EMAIL=${WP_EMAIL}
      - WP_USER2=${WP_USER2}
      - WP_EMAIL2=${WP_EMAIL2}
    secrets:
      - db_password
      - credentials
    volumes:
      - wordpress:/var/www/wordpress
    restart: unless-stopped
    networks:
      - inception

  adminer:
     build: ./requirements/bonus/adminer
     image: adminer:42
     depends_on:
       - mariadb
     container_name: adminer
     volumes:
      - adminer:/var/www/adminer
     restart: unless-stopped
     networks:
       - inception

  website:
    build: ./requirements/bonus/website
    image: website:42
    container_name: website
    volumes:
      - website:/var/www/website
    restart: unless-stopped
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx:42
    depends_on:
      - wordpress
      - adminer
      - website
    container_name: nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_USER=${DB_USER}
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - inception
