CREATE DATABASE IF NOT EXISTS MYSQL_DB;
CREATE USER IF NOT EXISTS 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PASS';
GRANT ALL PRIVILEGES ON MYSQL_DB.* TO 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PASS';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'MYSQL_RPASS';
FLUSH PRIVILEGES;
